name: CI
on:
  push:
    branches: [ main, develop ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: sync-data
        if: contains('[no-sync-data]', github.event.head_commit.message) == false
        run: echo "no sync"
