name: CI
on:
  push:
    branches: [ main, develop ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: sync-data
        if: ${{ github.event.label.name != 'no-sync-data' }}
        run: echo "sync data"
