name: CI
on:
  push:
    branches: [ main, develop ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: sync-data
        run: echo "${ github.event }"
